import React from "react";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dynamic | Checkout",
  description: "Generated by create next app",
};
const layout = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>;
};

export default layout;
