import Hero from "@/components/Hero";
import ProductSection from "@/components/ProductSection";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Teachify",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div>
      <Hero />
      <ProductSection />
    </div>
  );
}
