import { SignUp } from "@clerk/nextjs";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign up",
  description: "Generated by create next app",
};
export default function Page() {
  return <SignUp />;
}
